#!/bin/bash

# Get the C file name from the environment variable
CFILE="$CFILE"

# Create the output file name by replacing the extension with .s
ASMFILE="${CFILE%.c}.s"

# Generate the assembly code using gcc with the -S option
gcc -S -masm=intel "$CFILE" -o "$ASMFILE"
